### ISSUE TITLE
Remove requirement for `AWS_BUCKET_URL` or `BUCKETEER_BUCKET_URL` environment variable

### ISSUE THREAD

**Issue by crcastle** [fostive/gif-booth#2]
Bucketeer does not create or populate this environment variable, and its value can be constructed using the `BUCKETEER_BUCKET_NAME` or `AWS_BUCKET_NAME` environment variable.

So `config.js` can probably be changed like this:

```javascript
AWS_BUCKET_URL: `https://${process.env.BUCKETEER_BUCKET_NAME || process.env.AWS_BUCKET_NAME}.s3.amazonaws.com`
```

**Comment by vishalol** [comment]
@crcastle I would Iike to work on this. Can you please assign it to me

**Comment by crcastle** [comment]
Thank you @VishalCR7 ! Let me know if you have any questions. Please open a Pull Request when you're ready for us to review and merge your code.
