### ISSUE TITLE
Update to a generic FOSTIVE branding

### ISSUE THREAD

**Issue by julianduque** [fostive/gif-booth#24]
- [ ] Add a Powered by Fostive linking to the GitHub repo
- [x] Change colors to Fostive brand
- [x] Remove other event logos and branding
- [x] Add documentation on **How to customize the gif-booth app**

**Comment by justjenu** [comment]
@superhighfives for this and the other similar one can you either work with @clif-os or just update if it's easier/faster? we need to genericize these for future use. thanks much!

**Comment by superhighfives** [comment]
No worries! @DianaPerkinsDesign is looking after this for the emote widget, so may be able to do this at the same time. Let me know what you think Diana, or I can grab this one. 👍

**Comment by crcastle** [comment]
@DianaPerkinsDesign, @superhighfives, or @clif-os - Would one of you like to finish this? I *think* all the changes have been made but please verify (see checklist above). The only change missing is adding a "Brought to you with 💛 by Fostive" linking to https://github.com/fostive. See [this change](https://github.com/fostive/emote-widget/pull/31) made to the `emote-widget` app as an example.

**Comment by superhighfives** [comment]
@clif-os and I are unavailable for the short term, so it'd awesome if we could look at this when time permits, @DianaPerkinsDesign. 🙌  Thanks @crcastle.
